version: '3.1'
services:
  wordpress:
    depends_on:
      - db
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - ./:/var/www/html
    links:
      - db:mysql
    networks:
      - midlocode
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: developmentonly
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - midlocode
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8181:80
    environment:
      PMA_HOST: db
    links:
      - db:mysql
    networks:
      - midlocode
networks:
  midlocode:
    driver: bridge
volumes:
  db_data:
